format = """
[\\[ $username@$hostname | $directory\\]](cyan) [($git_branch$git_status)](yellow)
[>](fg:51) """

command_timeout = 2000

[username]
show_always = true
style_user = "bold cyan"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold cyan"
format = "[$hostname]($style)"

[directory]
style = "bold green"
truncate_to_repo = false
truncation_length = 0
home_symbol = "~"
read_only = " "

[git_branch]
format = "$branch"
style = "bold yellow"
only_attached = true

[git_status]
format = "$conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind"
conflicted = "*$count "
staged = "+$count "
modified = "!$count "
renamed = "➜$count "
deleted = "✖$count "
untracked = "?$count "
stashed = "⚑$count "
ahead = "↑$count"
behind = "↓$count"
diverged = "⇅${ahead_count}/${behind_count}"
style = "bold yellow"
ignore_submodules = true
