# ~/.config/starship.toml
add_newline = true

format = '''\[ $username@$hostname | $directory \] \($git_branch$git_status \)
> '''

[username]
format = "$user"
show_always = true
style_user = "bold white"

[hostname]
ssh_only = false
format = "$hostname"
style = "bold yellow"

[directory]
format = "$path"
home_symbol = "~"
style = "bold blue"

[git_branch]
symbol = ""
format = " ($branch)"
style = "bold magenta"

[git_status]
format = "$all_status"
conflicted = "!"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
untracked = "?"
stashed = "S"
modified = "*"
staged = "+"
renamed = "➜"
deleted = "x"
style = "bold red"
